gnupg2: Update to 2.2.25, fix +openldap on Big Sur
Update gnupg2 to the latest version 2.2.25.

| Noteworthy changes in version 2.2.25
| ====================================
|
|   * scd: Fix regression in 2.2.24 requiring gpg --card-status before
|     signing or decrypting.
|     https://dev.gnupg.org/T5065
|
|   * gpgsm: Using Libksba 1.5.0 signatures with a rarely used
|     combination of attributes can now be verified.
|     https://dev.gnupg.org/T5146
|
|   Release-info: https://dev.gnupg.org/T5140

Additionally, fix a failure to correctly compile against OpenLDAP when
+openldap is enabled (which is the default) due to
-Werror=implicit-function-declaration.

| conftest.c:84:1: error: implicit declaration of function 'ldap_open' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
| ldap_open("foobar",1234);
| ^
| conftest.c:84:1: note: did you mean 'ldap_turn'?
| /opt/local/include/ldap.h:2097:1: note: 'ldap_turn' declared here
| ldap_turn LDAP_P(( LDAP *ld,
| ^
| 1 error generated.

This happens because the configure script checks for ldap_open(3), which
was deprecated 20 years ago in [1], and hidden behind a preprocessor
define 16 years ago in [2]. With -Werror=implicit-function-declaration,
the unavailability of the function declaration makes the configure test
fail and gnupg2 build without LDAP support.

Fix this by adding -DLDAP_DEPRECATED=1 to the preprocessor flags, which
makes the configure test pass again. This is a stop-gap measure, and if
the LDAP support in gnupg depends on code that was deprecated 16 years
ago, maybe it should just be disabled, or at least removed from the
default variants.

[1]: https://git.openldap.org/openldap/openldap/-/commit/5417fdfea7004888c3f40840f8ed1c29fa738581
[2]: https://git.openldap.org/openldap/openldap/-/commit/4d29df5bd1fabcdc50975651c746365686b62b53

See: https://trac.macports.org/ticket/60583
See: https://github.com/macports/macports-ports/pull/2625
See: https://github.com/macports/macports-ports/pull/3214