qhull: require c++11
Build fails with errors like:
qhull-2020.1/src/libqhullcpp/QhullUser.h:39:41: error: a space is required between consecutive right angle brackets (use '> >')

Patching that allows the build to continue, but then it fails with:
user_eg3_r.cpp:350:28: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]

adding -std=c++11 and requesting in c++11 compatible compiler resolves it