gegl: define G_LOG_DOMAIN in Makefile not configure
Avoids error: use of undeclared identifier 'GEGL'.
Backport of
https://git.gnome.org/browse/gegl/commit/?id=81fb956b221e4b1f919788d8a5f6a3a5462b86ae

No revbump since port builds correctly or not at all.