SDRangel: fix build on macos <= 10.11
quick and dirty fix for
error: variable length array of non-POD element type 'complex<float>'

should be fine since it is a DSP library (DVB-S2 implementation) and
therefore not changed frequently; if something change, the patch fails
to apply.

Closes: https://trac.macports.org/ticket/59537