et: skip building test binaries
EternalTerminal-6.2.4/test/ServerFifoPathTest.cpp:3:10: fatal error: 'filesystem' file not found

test/ServerFifoPathTest.cpp directly includes the <filesystem> header,
which does not exist on macOS 10.14 and below.