hugin-app: build against boost 1.71
Building against boost 1.76, which is currently the default used by the boost
portgroup, fails with the following error:

:info:build Undefined symbols for architecture x86_64:
:info:build   "boost::filesystem::detail::recur_dir_itr_imp::increment(boost::system::error_code*)", referenced from:
:info:build       boost::filesystem::recursive_directory_iterator::increment() in pto_move.cpp.o
:info:build   "boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system:>
:info:build       boost::filesystem::directory_iterator::directory_iterator(boost::filesystem::path const&) in pto_move.cpp.o
:info:build   "boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, b>
:info:build       PTOCopyMove(bool, boost::filesystem::path, boost::filesystem::path, bool) in pto_move.cpp.o
:info:build   "boost::filesystem::absolute(boost::filesystem::path const&, boost::filesystem::path const&)", referenced from:
:info:build       RebaseFilename(boost::filesystem::path, boost::filesystem::path&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::alloc>
:info:build       checkDestinationDirectory(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, boost::filesystem::path&) >
:info:build       PTOCopyMove(bool, boost::filesystem::path, boost::filesystem::path, bool) in pto_move.cpp.o
:info:build       _main in pto_move.cpp.o
:info:build ld: symbol(s) not found for architecture x86_64
:info:build clang: error: linker command failed with exit code 1 (use -v to see invocation)

Boost 1.71 matches the version that was used before b25b206.

Fixes: https://trac.macports.org/ticket/63095