aacgain: fix compile on Tahoe (MacOS 26)
clang tries to compile this with C++11, resulting in compilation errors, e.g.
:info:build atom_standard.cpp:25:28: error: constant expression evaluates to 169 which cannot be narrowed to type 'char' [-Wc++11-narrowing]
:info:build    25 | static const char name[5]={0251,'n', 'a', 'm', '\0'};
:info:build       |                            ^~~~
Switching to older C++ standard resolves the issue