tk: fix configure error with XCode 12.3
* add patch to fix a warning now elevated to an error in newer XCode
releases, which causes a configure test to fail:

conftest.c:26:7: error: implicitly declaring library function 'exit'
  with type 'void (int) __attribute__((noreturn))'
  [-Werror,-Wimplicit-function-declaration]
        exit(2);
        ^
conftest.c:26:7: note: include the header <stdlib.h> or explicitly
  provide a declaration for 'exit'