KeePassXC: update -devel to the latest git revision
And blacklist Mac OS X < 10.8

The failiure in the autotype plugin on systems older than 10.8 was:
(see https://github.com/macports/macports-ports/pull/1411)

/usr/bin/clang++  -pipe -Os -stdlib=libstdc++ -fno-common -Wall -Wextra -Wundef -Wpointer-arith -Wno-long-long -Wformat=2 -Wmissing-format-attribute -fvisibility=hidden -fvisibility-inlines-hidden -fstack-protector-strong -fno-exceptions -fno-rtti -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Werror=format-security -std=c++11 -stdlib=libc++ -DNDEBUG -arch x86_64 -mmacosx-version-min=10.7 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -L/opt/local/lib -Wl,-headerpad_max_install_names CMakeFiles/testgroup.dir/TestGroup.cpp.o CMakeFiles/testgroup.dir/testgroup_autogen/mocs_compilation.cpp.o  -o testgroup -Wl,-rpath,/opt/local/lib ../src/libkeepassx_core.a /opt/local/libexec/qt5/lib/QtTest.framework/QtTest /opt/local/lib/libgcrypt.dylib /opt/local/lib/libgpg-error.dylib /opt/local/lib/libz.dylib ../src/libautotype.a ../src/http/libkeepasshttp.a ../src/http/qhttp/libqhttp.a ../src/browser/libkeepassxcbrowser.a /opt/local/libexec/qt5/lib/QtConcurrent.framework/QtConcurrent /opt/local/lib/libsodium.dylib ../src/sshagent/libsshagent.a /opt/local/libexec/qt5/lib/QtWidgets.framework/QtWidgets /opt/local/libexec/qt5/lib/QtNetwork.framework/QtNetwork /opt/local/lib/libcurl.dylib ../src/libzxcvbn.a /opt/local/lib/libargon2.dylib /opt/local/lib/libgcrypt.dylib /opt/local/lib/libgpg-error.dylib /opt/local/lib/libz.dylib -framework Foundation /opt/local/libexec/qt5/lib/QtMacExtras.framework/QtMacExtras /opt/local/libexec/qt5/lib/QtGui.framework/QtGui /opt/local/libexec/qt5/lib/QtCore.framework/QtCore
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_security_KeePassXC/KeePassXC/work/keepassxc-2.3.1/src/autotype/mac/AppKitImpl.mm:46:33: error: expected method to read dictionary element not found on object of type 'NSDictionary *'
    NSRunningApplication *app = userInfo[NSWorkspaceApplicationKey];
                                ^

Since https://github.com/keepassxreboot/keepassxc/commit/5488f1bfc336219bed677e67a63954c3959ecace,
relevant code is also used in the main program, so building on <10.8 does
not work at all.