py-python-install: Add importlib-metadata dep for <= 37
On Python <= 3.7, py-python-install needs importlib_metadata, provided
by the py-importlib-metadata port as dependency.

Add that as depends_lib and revbump to fix broken installations.

Lack of this module causes builds of dependent ports to fail in trace
mode:

| :debug:destroot system:  cd "/opt/local/var/macports/build/_opt_dports_python_py-packaging/py37-packaging/work/packaging-20.7" && /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -m install --verbose /opt/local/var/macports/build/_opt_dports_python_py-packaging/py37-packaging/work/packaging-20.7-py2.py3-none-any.whl --destdir /opt/local/var/macports/build/_opt_dports_python_py-packaging/py37-packaging/work/destroot
| :info:destroot ['/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/install/_vendor/installer/src', '/opt/local/var/macports/build/_opt_dports_python_py-packaging/py37-packaging/work/packaging-20.7', '/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python37.zip', '/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7', '/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload', '/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages']
| :info:destroot Traceback (most recent call last):
| :info:destroot   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/install/__main__.py", line 115, in <module>
| :info:destroot     build(args.wheel, cache_dir, args.optimize, args.verify_dependencies)
| :info:destroot   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/install/__init__.py", line 226, in build
| :info:destroot     _verify_compability(dist_info, verify_dependencies)
| :info:destroot   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/install/__init__.py", line 173, in _verify_compability
| :info:destroot     dist = importlib_metadata.Distribution.at(dir)
| :info:destroot AttributeError: module 'importlib_metadata' has no attribute 'Distribution'
| :info:destroot ERROR module 'importlib_metadata' has no attribute 'Distribution'
| :info:destroot Command failed:  cd "/opt/local/var/macports/build/_opt_dports_python_py-packaging/py37-packaging/work/packaging-20.7" && /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -m install --verbose /opt/local/var/macports/build/_opt_dports_python_py-packaging/py37-packaging/work/packaging-20.7-py2.py3-none-any.whl --destdir /opt/local/var/macports/build/_opt_dports_python_py-packaging/py37-packaging/work/destroot
| :info:destroot Exit code: 1
| :warn:destroot The following existing files were hidden from the build system by trace mode:
| :msg:destroot   /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/importlib_metadata/__init__.py
| :msg:destroot   /var/root/.CFUserTextEncoding
| :error:destroot Failed to destroot py37-packaging: command execution failed