KeePassXC-devel: update to latest devel & update patch
Update patch to fix build on macos

Fixes these build errors on macos 10.8

/src/touchid/TouchID.mm:132:5: error: unknown type name 'SecAccessControlCreateFlags'
/src/touchid/TouchID.mm:148:4: error: use of undeclared identifier 'SecAccessControlRef'

Fix build when built with Qt5.6 (used on macos 10.7)