py-pint: update to 0.12, add py38 subport
- switch to PyPI because the latest version does not build from GitHub:
LookupError: setuptools-scm was unable to detect version. Make sure
you're either building from a fully intact git repository or PyPI tarballs.
- pin to 0.9 for PY27 and PY35