qtiplot: fix build on newer version of Clang
Avoid
    error: ordered comparison between pointer and zero
           ('const void *' and 'int')

No revbump since port either builds correctly or not at all.