libassuan: fix build on Tiger
error: 'fd_set' undeclared
this is defined in <sys/select.h> on Tiger
also remove INADDR_LOOPBACK patch that is now integrated upstream

passes all tests on Tiger after this patch