Revert "macports-libcxx: clear configure.compiler so universal is respected"
This reverts commit 46b32e2969e2db44495737a9233bf9d99a961089.

sadly -- despite looking very promising -- this did not work as written.

--->  Configuring macports-libcxx
Error: Failed to configure macports-libcxx: Invalid value for configure.compiler:
DEBUG: Error code: NONE
DEBUG: Backtrace: Invalid value for configure.compiler:

back to the drawing board.