borgmatic: Add missing py-packaging dependency
```
:) cllang@cllang-mac:[…]/sysutils/borgmatic$ borgmatic --help
Traceback (most recent call last):
[…]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/borgmatic/borg/feature.py", line 3, in <module>
    from packaging.version import parse
ModuleNotFoundError: No module named 'packaging'
```