py-cvxopt: conflict with atlas if Accelerate used
revbump since port can build successfully but fail at runtime:
    ImportError: dlopen(...): Symbol not found: _ATL_cGetNB